# Generated by Django 5.1.4 on 2025-01-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebamod2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['headline'], 'verbose_name': 'Noticia'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['id'], 'verbose_name': 'Publication'},
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='Noticia',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='Publication',
        ),
    ]
